lib/ranker_web/router.ex
defmodule RankerWeb.Router do
  use RankerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RankerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/players/new", PlayerController, :new
    post "/players", PlayerController, :create
    get "/players", PlayerController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RankerWeb do
  #   pipe_through :api
  # end
end

lib/ranker/application.ex
defmodule Ranker.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Ranker.Repo, []),
      # Start the endpoint when the application starts
      supervisor(RankerWeb.Endpoint, []),
      # Start your own worker by calling: Ranker.Worker.start_link(arg1, arg2, arg3)
      # worker(Ranker.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Ranker.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    RankerWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/ranker/player.ex
defmodule Ranker.Player do
  use Ecto.Schema
  import Ecto.Changeset


  schema "players" do
    field :name, :string
    field :rank, :integer

    timestamps()
  end

  @doc false
  def changeset(player, attrs) do
    player
    |> cast(attrs, [:name, :rank])
    |> validate_required([:name, :rank])
  end
end

lib/ranker/repo.ex
defmodule Ranker.Repo do
  use Ecto.Repo, otp_app: :ranker

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/ranker_web/controllers/page_controller.ex
defmodule RankerWeb.PageController do
  use RankerWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/ranker_web/controllers/player_controller.ex
defmodule RankerWeb.PlayerController do
  use RankerWeb, :controller

  alias Ranker.Player
  alias Ranker.Repo

  def index(conn, _params) do
    players = Repo.all(Player)
    render conn, "index.html", players: players
  end

  def new(conn, _params) do
    changeset = Player.changeset(%Player{}, %{})

    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"player" => player}) do
    changeset = Player.changeset(%Player{}, player)

    case Repo.insert(changeset) do
      {:ok, _player} ->
        conn
        |> put_flash(:info, "Player Added")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

end

lib/ranker_web/views/error_view.ex
defmodule RankerWeb.ErrorView do
  use RankerWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/ranker_web/views/layout_view.ex
defmodule RankerWeb.LayoutView do
  use RankerWeb, :view
end

lib/ranker_web/views/page_view.ex
defmodule RankerWeb.PageView do
  use RankerWeb, :view
end

lib/ranker_web/views/player_view.ex
defmodule RankerWeb.PlayerView do
  use RankerWeb, :view
end

lib/ranker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GameRanker!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <nav class="green">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Pool Ranker
        </a>
      </div>
    </nav>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/ranker_web/templates/page/index.html.eex
<h5>Welcome</h5>
<%= link to: player_path(@conn, :new), class: "btn blue" do %>
  Add a player
<% end %>

<%= link to: player_path(@conn, :index), class: "btn green" do %>
  View Players
<% end %>

<div class="btn green">
  View a player
</div>
<div class="btn blue">
  Report a game
</div>

lib/ranker_web/templates/player/index.html.eex
<h5>Players</h5>

<ul class="collection">
  <%= for player <- @players do %>
    <li class="collection-item">
      <%= player.name %>
      <%= player.rank %>
    </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: player_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

lib/ranker_web/templates/player/new.html.eex
<%= form_for @changeset, player_path(@conn, :create), fn f-> %>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
    <%= error_tag f, :name %>
    <%= text_input f, :rank, placeholder: "Rank", class: "form-control" %>
    <%= error_tag f, :rank %>
  </div>

    <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>